### ISSUE TITLE
How to Install

### ISSUE THREAD

**Issue by kitt2011** [wlemkens/hass-ecometers#1]
Hello, 

first big Thanks for your work!
But can you please tell me how to integrate this in Homeassistant?
Thank you very much

**Comment by wlemkens** [comment]
Hi. Nice to see someone using the sensor.

I have updated the Readme. Could you take a look, see if it is clear and let me know if you have any problems installing?

**Comment by kitt2011** [comment]
Thank you!

i have the first problem with testing the component. When i use putty and send "cd $CONFIG/custom_components/hass-ecometers/ecometers/example/
ptyhon example.py /dev/YOUR_USB_PORT"  (You must correct PTYHON with PYTHON :) )
and i use my usb port "tyusb1"
Putty says:
"" cd $CONFIG/custom_components/hass-ecometers/ecometers/example/
python example.py /dev/ttyUSB1"" 
-bash: cd: /custom_components/hass-ecometers/ecometers/example/: No such file or directory
-bash: python: command not found

the direction is correct an i have copied all of your data
Thank you!

**Comment by kitt2011** [comment]
Okay, the correct line is "cd config/custom_components/hass-ecometers/ecometers/example/" to go to the correct dictionary. Putty seems to have problems with "$CONFIG"

but the other problem "
-bash: python: command not found
"
remains.

**Comment by wlemkens** [comment]
Thanks for the reply.

The CONFIG environment variable seems not to be set. Make sure to set it (in the same terminal) as described some steps earlier: `export CONFIG=/PATH_TO_YOUR_CONFIG`. Otherwise you end up in the wrong directory.

Ca it be that python is not yet installed? If you are running on Ubuntu/Debian/Raspian you do that with `sudo apt install python`

**Comment by kitt2011** [comment]
i think you will be right that python is not installed. Home assistant runs as OS directly from the SD card and not on Ubuntu/Debian or similar. So unfortunately I can not install Python so, I have python_script installed. Or Is it then not possible to use the sensor in my installation?

**Comment by wlemkens** [comment]
I have no experience with Home Assistant OS, but I think the component should work. You might not be able to run the test however. 

You can skip the test since it just to get an early diagnosis the connection works. It is not essential.

**Comment by kitt2011** [comment]
Your right, i skipped the test. After the reboot i see the entities. Now i wait an hour and hope, that then i see the values :) Thank you! 
![image](https://user-images.githubusercontent.com/86961971/190164216-b60eb208-1026-4e48-8887-a143e620a3d6.png)

**Comment by wlemkens** [comment]
Nice! 

Just to be sure, you probably know, but you won't see any values in the entity tab. You need to add it to a dashboard.

Let me know if you encounter any problems.

**Comment by kitt2011** [comment]
yes of course i have created a dashboard with the entities. 
Unfortunately I have not received any values yet. The USB Prot is definitely correct and there are no error messages in the log.

I changed the USB port, then the log also says as error message "no serial data received".

Speaks for me that the USB port is correct and receives data. I just do not know why these are not displayed.

**Comment by curantil** [comment]
Could you enable debug logging for the component? Add the following to configuration.yaml and restart Home Assistant (you don't need to reboot):
'''
logger:
  default: warning
  logs:
    custom_components.hass-ecometers: debug
    root: debug
'''
If any of these lines are already in you config, don't re-add them, but put the rest that isn't there underneath.

After restarting there should be some things related to the ecometer in the logs. What do they say?

**Comment by wlemkens** [comment]
Could you enable debug logging for the component? Add the following to configuration.yaml and restart Home Assistant (you don't need to reboot):

```
logger:
  default: warning
  logs:
    custom_components.hass-ecometers: debug
    root: debug
```
If any of these lines are already in you config, don't re-add them, but put the rest that isn't there underneath.

After restarting there should be some things related to the ecometer in the logs. What do they say?

**Comment by kitt2011** [comment]
hello, today I wanted to revise the configuration and activate the logging and have seen that now after 2 / 3 days but suddenly data are displayed on the dashboard :) I'm trying with it now times around.  Is the height and the offset in the configuration necessary? Since I have already set the data in the Ecometer itself. and if so, in what unit are these?

**Comment by wlemkens** [comment]
The height and offset are important since I'm not able to get the configuration from the display. The data only contains the distance measurement, so I need to extract the distance from the height + offset.

The units are cm.

I assume you have a vertical cylindrical tank? 

Do you have a dead zone configured in you display? I've not implemented that yet since I don't use it myself. But I can do that easily.

**Comment by kitt2011** [comment]
![image](https://user-images.githubusercontent.com/86961971/191171340-44e166e3-b187-4e2a-a74d-87637ce897d5.png)
![WhatsApp Image 2022-09-19 at 11 03 50](https://user-images.githubusercontent.com/86961971/191171385-0c9d4a3f-36f5-4bed-a22b-68201cfbc0ba.jpeg)

![image](https://user-images.githubusercontent.com/86961971/191171937-08bf27d7-2b37-4f55-ae4b-2d53b8cda981.png)

![image](https://user-images.githubusercontent.com/86961971/191172263-ee3a8f69-dc57-465b-9ec0-98ef349c8598.png)

Strangely, your configuration does not need the height and offset for me. I have entered absurd values as a test (height 1600cm offset 200cm) (it generally does not matter what I enter here because the values in my dashboard always remain the same).
The tank filling in % and the tank volume always remains the same (at different heights and offset values). Currently at 30% and 1316L.
These are also 100% the same values as my display outputs.

However, I noticed that the sensor is updated only once a day (every day at 21:15 approximately) or gets new values. I thought that the sensor is updated in 30 minute intervals

The next is the tank temperature (really tank or is it the room temperature of the display?)

This always oscillates between the real value and as if the temperature sensor was not connected. I could solve this with a filter from the Home Assistant.

I do not have a cylindrical tank but one like in the picture.

These have 1500L (times 3) 100L in each tank remains above air. This means 4500L tank and maximum 4200L capacity.

I can give you times through what I have on the display for settings which also work well for years.

Tank type: B
Max. Volume: 4500L
Filling height in cm: 145cm
Width of the tank in CM: 70cm

I do not have more settings.
That was a lot of information. And maybe you have some more good answers for me :) Thank you so far!

**Comment by wlemkens** [comment]
The level (in cm) should make use of the configured height and offset. Volume in liters and percentage will work without.

Tank type B is not yet implemented. The volume in liters and percentage will work fine, but the level in cm will not be correct. I'll try to implement that asap.

The temperature is indeed the temperature in the tank (at the sensor) contrary to the temperature on the display which is the room temperature.

Strange that you only get updates once a day. I get updates every 30 minutes or so as expected. Your temperature measurements seem to be updated more however. Although they should not oscillate like that.


Is something visible in the logs? Could you share those?

**Comment by wlemkens** [comment]
Actually, after looking into it, the tank type doesn't seems to matter for the HA component since it receives the total volume and the usable volume anyway. It would only matter if the volume needed to be calculated from the distance measurement.

However, to get the correct level in cm, the tank height + offset still needs to be the same as configured in the display.

**Comment by wlemkens** [comment]
Did you manage to fix it or get any logs?

**Comment by kitt2011** [comment]
Hello,

sorry for the late feedback my home assistant died (sd card) and now have it running again for 3 days on a new ssd.

So for me only the remaining liters in the tank are interesting. That is also satisfied displayed but maximum only updated once a day, if not every 3 days.
The problem is not the home assistant integration but the ecometer itself. Because the display updates just as sluggish or every few days only. The Home assistant shows the same values as on the display! However, the display updates only so slowly

in the logs are no entries available.

Translated with www.DeepL.com/Translator (free version)

**Comment by wlemkens** [comment]
Ok, then I'll consider it as not an issue with the software and close the issue.
